version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: iot-mysql
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: iot-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=iot-mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mysql
    networks:
      - iot-network

volumes:
  mysql-data:

networks:
  iot-network:
    driver: bridge
