version: "3.7"
services: 
  mysql:
    image: mysql:latest
    container_name: iot-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - './docker/config/mysql:/var/lib/mysql'
  app:
    image: app
    container_name: nodejs-server
    build:
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  
  